import type {
  AlertsPayload,
  ClientDetailPayload,
  ClientRecord,
  DashboardPayload,
  DistributionPagePayload,
  DistributionRecord,
  ExpenseCategoryRecord,
  ExpenseRecord,
  IncomeRecord,
  ProjectDetailPayload,
  ProjectRecord,
  RecurringExpenseRecord,
  SalaryRecord,
  ScheduledExpenseRecord,
  ScheduledPaymentRecord,
} from "@/lib/types";

export const demoClients: ClientRecord[] = [
  {
    id: "client-pacsa",
    name: "PACSA",
    contactName: "Paula Sánchez",
    contactEmail: "paula@pacsa.com",
    contactPhone: "+54 9 11 5555 0191",
    notes: "Automatizaciones comerciales",
    totalInvoicedUsd: 11200,
    totalReceivableUsd: 2400,
    activeProjects: 2,
    totalProjects: 2,
  },
  {
    id: "client-colegio",
    name: "COLEGIO",
    contactName: "Marina Díaz",
    contactEmail: "marina@colegio.edu.ar",
    contactPhone: "+54 9 11 5555 0192",
    notes: "Implementación operativa y mantenimiento",
    totalInvoicedUsd: 8900,
    totalReceivableUsd: 1850,
    activeProjects: 1,
    totalProjects: 1,
  },
  {
    id: "client-faufena",
    name: "FAUFENA",
    contactName: null,
    contactEmail: null,
    contactPhone: null,
    notes: "Sitio institucional",
    totalInvoicedUsd: 5200,
    totalReceivableUsd: 0,
    activeProjects: 0,
    totalProjects: 1,
  },
];

export const demoProjects: ProjectRecord[] = [
  {
    id: "project-whatsapp",
    clientId: "client-pacsa",
    clientName: "PACSA",
    name: "Automatización WhatsApp",
    status: "ACTIVE",
    devBudgetUsd: 10000,
    monthlyFeeUsd: 900,
    monthlyFeeEndDate: "2026-04-05",
    notes: "Pipeline comercial y recordatorios",
    pendingIncomeCount: 1,
    developmentCollectedUsd: 4600,
    maintenanceCollectedUsd: 3000,
    developmentPendingUsd: 5400,
    totalCollectedUsd: 7600,
    nextPaymentDate: "2026-03-18",
  },
  {
    id: "project-analytics",
    clientId: "client-pacsa",
    clientName: "PACSA",
    name: "Tablero Analytics",
    status: "ACTIVE",
    devBudgetUsd: 4200,
    monthlyFeeUsd: 450,
    monthlyFeeEndDate: null,
    notes: null,
    pendingIncomeCount: 0,
    developmentCollectedUsd: 3600,
    maintenanceCollectedUsd: 0,
    developmentPendingUsd: 600,
    totalCollectedUsd: 3600,
    nextPaymentDate: "2026-03-28",
  },
  {
    id: "project-mantenimiento",
    clientId: "client-colegio",
    clientName: "COLEGIO",
    name: "Mantenimiento Web",
    status: "ACTIVE",
    devBudgetUsd: null,
    monthlyFeeUsd: 950,
    monthlyFeeEndDate: "2026-03-31",
    notes: "Contrato recurrente",
    pendingIncomeCount: 1,
    developmentCollectedUsd: 0,
    maintenanceCollectedUsd: 5200,
    developmentPendingUsd: null,
    totalCollectedUsd: 5200,
    nextPaymentDate: "2026-03-20",
  },
  {
    id: "project-faufena-site",
    clientId: "client-faufena",
    clientName: "FAUFENA",
    name: "Sitio Institucional",
    status: "COMPLETED",
    devBudgetUsd: 5200,
    monthlyFeeUsd: null,
    monthlyFeeEndDate: null,
    notes: null,
    pendingIncomeCount: 0,
    developmentCollectedUsd: 5200,
    maintenanceCollectedUsd: 0,
    developmentPendingUsd: 0,
    totalCollectedUsd: 5200,
    nextPaymentDate: null,
  },
];

export const demoIncomes: IncomeRecord[] = [
  {
    id: "inc-1",
    projectId: "project-whatsapp",
    projectName: "Automatización WhatsApp",
    clientName: "PACSA",
    date: "2026-01-12",
    dueDate: null,
    amountArs: null,
    amountUsd: 2400,
    exchangeRate: null,
    status: "PAID",
    displayStatus: "PAID",
    type: "DEVELOPMENT",
    notes: "Primer adelanto",
  },
  {
    id: "inc-2",
    projectId: "project-whatsapp",
    projectName: "Automatización WhatsApp",
    clientName: "PACSA",
    date: "2026-02-15",
    dueDate: null,
    amountArs: 2280000,
    amountUsd: 2200,
    exchangeRate: 1036,
    status: "PAID",
    displayStatus: "PAID",
    type: "DEVELOPMENT",
    notes: "Segundo hito",
  },
  {
    id: "inc-3",
    projectId: "project-analytics",
    projectName: "Tablero Analytics",
    clientName: "PACSA",
    date: "2026-02-03",
    dueDate: null,
    amountArs: null,
    amountUsd: 1800,
    exchangeRate: null,
    status: "PAID",
    displayStatus: "PAID",
    type: "DEVELOPMENT",
    notes: null,
  },
  {
    id: "inc-4",
    projectId: "project-mantenimiento",
    projectName: "Mantenimiento Web",
    clientName: "COLEGIO",
    date: "2026-03-01",
    dueDate: null,
    amountArs: null,
    amountUsd: 950,
    exchangeRate: null,
    status: "PAID",
    displayStatus: "PAID",
    type: "MAINTENANCE",
    notes: "Febrero pagado",
  },
  {
    id: "inc-5",
    projectId: "project-faufena-site",
    projectName: "Sitio Institucional",
    clientName: "FAUFENA",
    date: "2025-12-11",
    dueDate: null,
    amountArs: null,
    amountUsd: 5200,
    exchangeRate: null,
    status: "PAID",
    displayStatus: "PAID",
    type: "DEVELOPMENT",
    notes: "Proyecto cerrado",
  },
];

export const demoCategories: ExpenseCategoryRecord[] = [
  { id: "cat-software", name: "Herramientas/Software", isDefault: true },
  { id: "cat-cloud", name: "Infra/Cloud", isDefault: true },
  { id: "cat-salary", name: "Sueldos/Honorarios", isDefault: true },
  { id: "cat-marketing", name: "Marketing", isDefault: true },
];

export const demoExpenses: ExpenseRecord[] = [
  {
    id: "exp-1",
    date: "2026-01-09",
    categoryId: "cat-software",
    categoryName: "Herramientas/Software",
    expenseType: "fixed",
    projectId: null,
    projectName: null,
    amountArs: null,
    amountUsd: 120,
    exchangeRate: null,
    description: "ChatGPT Teams",
    salaryWithdrawalId: null,
    scheduledExpenseId: null,
    notes: null,
  },
  {
    id: "exp-2",
    date: "2026-02-04",
    categoryId: "cat-cloud",
    categoryName: "Infra/Cloud",
    expenseType: "fixed",
    projectId: "project-whatsapp",
    projectName: "Automatización WhatsApp",
    amountArs: null,
    amountUsd: 210,
    exchangeRate: null,
    description: "Vercel + Neon",
    salaryWithdrawalId: null,
    scheduledExpenseId: null,
    notes: null,
  },
  {
    id: "exp-3",
    date: "2026-03-06",
    categoryId: "cat-salary",
    categoryName: "Sueldos/Honorarios",
    expenseType: "fixed",
    projectId: null,
    projectName: null,
    amountArs: null,
    amountUsd: 1600,
    exchangeRate: null,
    description: "Salario Tomas - Mar 2026",
    salaryWithdrawalId: "salary-1",
    scheduledExpenseId: null,
    notes: null,
  },
  {
    id: "exp-4",
    date: "2026-03-07",
    categoryId: "cat-marketing",
    categoryName: "Marketing",
    expenseType: "variable",
    projectId: "project-analytics",
    projectName: "Tablero Analytics",
    amountArs: 580000,
    amountUsd: 560,
    exchangeRate: 1035.71,
    description: "Campaña Meta Ads",
    salaryWithdrawalId: null,
    scheduledExpenseId: null,
    notes: null,
  },
];

export const demoRecurringExpenses: RecurringExpenseRecord[] = [
  {
    id: "rexp-1",
    description: "ChatGPT Team",
    categoryId: "cat-software",
    categoryName: "Herramientas/Software",
    amountUsd: 120,
    startDate: "2026-01-01",
    frequency: "monthly",
    isActive: true,
    nextDueDate: "2026-03-22",
    pendingCount: 3,
  },
  {
    id: "rexp-2",
    description: "Estudio contable",
    categoryId: "cat-marketing",
    categoryName: "Marketing",
    amountUsd: 180,
    startDate: "2026-01-01",
    frequency: "monthly",
    isActive: true,
    nextDueDate: "2026-03-25",
    pendingCount: 2,
  },
];

export const demoScheduledExpenses: ScheduledExpenseRecord[] = [
  {
    id: "sexp-1",
    recurringExpenseId: "rexp-1",
    description: "ChatGPT Team",
    categoryId: "cat-software",
    categoryName: "Herramientas/Software",
    dueDate: "2026-03-22",
    amountUsd: 120,
    status: "PENDING",
    paidAt: null,
    actualExpenseId: null,
  },
  {
    id: "sexp-2",
    recurringExpenseId: "rexp-2",
    description: "Estudio contable",
    categoryId: "cat-marketing",
    categoryName: "Marketing",
    dueDate: "2026-03-10",
    amountUsd: 180,
    status: "PENDING",
    paidAt: null,
    actualExpenseId: null,
  },
];

export const demoLayers: DistributionRecord[] = [
  {
    id: "layer-emergency",
    layer: "emergency",
    currentAmountUsd: 2000,
    storageLocation: "Cocos Capital",
  },
  {
    id: "layer-growth",
    layer: "growth",
    currentAmountUsd: 4000,
    storageLocation: "Naranja X",
  },
];

export const demoSalaries: SalaryRecord[] = [
  {
    id: "salary-1",
    personName: "Tomas",
    month: "2026-03-01",
    date: "2026-03-06",
    amountUsd: 1600,
    amountArs: null,
    exchangeRate: null,
    notes: "Retiro operativo",
  },
];

export const demoScheduledPayments: ScheduledPaymentRecord[] = [
  {
    id: "pay-1",
    projectId: "project-mantenimiento",
    projectName: "Mantenimiento Web",
    clientName: "COLEGIO",
    type: "MAINTENANCE",
    expectedDate: "2026-03-20",
    expectedAmountUsd: 950,
    status: "pending",
    paidAt: null,
    actualIncomeId: null,
    notes: "Factura enviada",
  },
  {
    id: "pay-2",
    projectId: "project-whatsapp",
    projectName: "Automatización WhatsApp",
    clientName: "PACSA",
    type: "DEVELOPMENT",
    expectedDate: "2026-03-18",
    expectedAmountUsd: 2400,
    status: "pending",
    paidAt: null,
    actualIncomeId: null,
    notes: "Cierre del proyecto",
  },
  {
    id: "pay-3",
    projectId: "project-analytics",
    projectName: "Tablero Analytics",
    clientName: "PACSA",
    type: "DEVELOPMENT",
    expectedDate: "2026-03-10",
    expectedAmountUsd: 600,
    status: "overdue",
    paidAt: null,
    actualIncomeId: null,
    notes: "Pendiente de cobranza",
  },
];

export const demoAlerts: AlertsPayload = {
  overdue: {
    count: 1,
    totalUsd: 600,
    items: demoScheduledPayments.filter((item) => item.status === "overdue"),
  },
  upcoming7Days: {
    count: 2,
    totalUsd: 3350,
    items: demoScheduledPayments.filter((item) => item.status === "pending"),
  },
  upcoming30Days: {
    count: 2,
    totalUsd: 3350,
    items: demoScheduledPayments.filter((item) => item.status === "pending"),
  },
  subscriptionsEndingSoon: {
    count: 2,
    items: demoProjects
      .filter((project) => project.monthlyFeeEndDate)
      .map((project) => ({
        projectId: project.id,
        projectName: project.name,
        clientName: project.clientName,
        monthlyFeeUsd: project.monthlyFeeUsd ?? 0,
        endDate: project.monthlyFeeEndDate!,
        daysRemaining: project.monthlyFeeEndDate === "2026-03-31" ? 15 : 20,
      })),
  },
};

export const demoDistributionPage: DistributionPagePayload = {
  layers: demoLayers,
  summary: {
    totalIncomeUsd: 12550,
    totalExpenseUsd: 2490,
    netResultUsd: 10060,
    remanenteUsd: 4060,
  },
  salaries: demoSalaries,
};

export const demoDashboard: DashboardPayload = {
  filters: {
    from: null,
    to: null,
    clientId: null,
    projectId: null,
  },
  kpis: {
    incomesUsd: 12550,
    expensesUsd: 2490,
    netUsd: 10060,
    remanenteUsd: 4060,
    receivableUsd: 3950,
    overdueUsd: 600,
    committedExpensesMonthUsd: 300,
    salariesThisMonthUsd: 1600,
  },
  charts: {
    monthlyPerformance: [
      { month: "Jan", incomeUsd: 2400, expenseUsd: 120, netUsd: 2280 },
      { month: "Feb", incomeUsd: 4000, expenseUsd: 210, netUsd: 3790 },
      { month: "Mar", incomeUsd: 6150, expenseUsd: 2160, netUsd: 3990 },
    ],
    categoryBreakdown: [
      { category: "Sueldos/Honorarios", amountUsd: 1600 },
      { category: "Marketing", amountUsd: 560 },
      { category: "Infra/Cloud", amountUsd: 210 },
      { category: "Herramientas/Software", amountUsd: 120 },
    ],
    cumulativeCashflow: [
      { month: "Jan", valueUsd: 2280 },
      { month: "Feb", valueUsd: 6070 },
      { month: "Mar", valueUsd: 10060 },
    ],
    topClients: [
      { clientName: "PACSA", incomeUsd: 7600, activeProjects: 2, pendingPayments: 2 },
      { clientName: "COLEGIO", incomeUsd: 5200, activeProjects: 1, pendingPayments: 1 },
      { clientName: "FAUFENA", incomeUsd: 5200, activeProjects: 0, pendingPayments: 0 },
    ],
  },
  upcomingPayments: demoScheduledPayments,
  distribution: demoLayers,
  alerts: demoAlerts,
};

export const demoClientDetails = new Map<string, ClientDetailPayload>(
  demoClients.map((client) => [
    client.id,
    {
      client,
      projects: demoProjects.filter((project) => project.clientId === client.id),
      incomes: demoIncomes.filter((income) => demoProjects.find((project) => project.id === income.projectId)?.clientId === client.id),
      payments: demoScheduledPayments.filter(
        (payment) => demoProjects.find((project) => project.id === payment.projectId)?.clientId === client.id,
      ),
    },
  ]),
);

export const demoProjectDetails = new Map<string, ProjectDetailPayload>(
  demoProjects.map((project) => [
    project.id,
    {
      project,
      incomes: demoIncomes.filter((income) => income.projectId === project.id),
      scheduledPayments: demoScheduledPayments.filter((payment) => payment.projectId === project.id),
      expenses: demoExpenses.filter((expense) => expense.projectId === project.id),
    },
  ]),
);
